name: Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '!main'

jobs:
  windows-latest:
    name: windows-2022
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Nuke Build
        run: ./.nuke/build.cmd